### ISSUE TITLE
Adding support for Arctis 5 2019 edition.

### ISSUE THREAD

**Issue by foonly** [DemonTPx/steelseries-arctis-5-pulseaudio-profile#2]
This works for the 2019 edition as well, but udev doesn't detect it because of new HW id.
The id is: 1038:12aa

I fixed it by adding a second line to the udev rules:
ATTRS{idVendor}=="1038", ATTRS{idProduct}=="12aa", ENV{PULSE_PROFILE_SET}="steelseries-arctis-5-usb-audio.conf"

But there might be a better way.

**Comment by DemonTPx** [comment]
Good to know that the new version also works!

I think that is the correct way to add it, could you please make a PR with that change? I'll create a new release (.deb file) for it after that :)

**Comment by DemonTPx** [comment]
Here it is: https://github.com/DemonTPx/steelseries-arctis-5-pulseaudio-profile/releases/tag/0.3

Thanks for submitting the PR :+1:
